version: '3.8'

services:
  app:
    build: .
    container_name: todo-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/todo-app
    depends_on:
      - mongo
    volumes:
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
